services:
  gateway:
    container_name: gateway_service
    build: ./gateway_service
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - member_service
      - feedback_service

  member_service:
    image: alpine:latest
    container_name: member_service_placeholder
    command: ["sh", "-c", "while true; do sleep 3600; done"]

  feedback_service:
    container_name: feedback_service
    build: ./feedback_service
    env_file: .env
    ports:
      - "8002:8000"
    depends_on:
      - feedback_db

  feedback_db:
    container_name: feedback_db
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${FEEDBACK_DB_NAME}
      - POSTGRES_USER=${FEEDBACK_DB_USER}
      - POSTGRES_PASSWORD=${FEEDBACK_DB_PASS}
    volumes:
      - feedback_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  feedback_data: