services:
  gateway:
    # Mount the local code into the container
    volumes:
      - ./gateway_service/app:/app/app
      - ./gateway_service/requirements.txt:/app/requirements.txt
      - ./gateway_service/Dockerfile:/app/Dockerfile
    # Override the startup command to use reload
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  feedback_service:
    volumes:
      - ./feedback_service/app:/app/app
      - ./feedback_service/requirements.txt:/app/requirements.txt
      - ./feedback_service/Dockerfile:/app/Dockerfile
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  # member_service:
  #   volumes:
  #     - ./member_service/app:/app/app
  #     - ./member_service/requirements.txt:/app/requirements.txt
  #     - ./member_service/Dockerfile:/app/Dockerfile
  #   command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
