services:
  gateway:
    container_name: gateway_service
    build: ./gateway_service
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - member_service
      - feedback_service

  member_service:
    image: alpine:latest
    container_name: member_service
    build: ./member_service
    env_file: .env
    ports:
      - "8001:8000"
    depends_on:
      - member_db

  member_db:
    container_name: member_db
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${MEMBER_DB_NAME}
      - POSTGRES_USER=${MEMBER_DB_USER}
      - POSTGRES_PASSWORD=${MEMBER_DB_PASS}
    volumes:
      - member_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  feedback_service:
    container_name: feedback_service
    build: ./feedback_service
    env_file: .env
    ports:
      - "8002:8000"
    depends_on:
      - feedback_db

  feedback_db:
    container_name: feedback_db
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${FEEDBACK_DB_NAME}
      - POSTGRES_USER=${FEEDBACK_DB_USER}
      - POSTGRES_PASSWORD=${FEEDBACK_DB_PASS}
    volumes:
      - feedback_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  feedback_data:
  member_data: